//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Bill_ID { get; set; }
        public int Bill_no { get; set; }
        public System.DateTime Billing_date { get; set; }
        public double Amount { get; set; }
        public string Account_status { get; set; }
        public Nullable<double> Discount { get; set; }
        public double Total_amount { get; set; }
    }
}
