//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int App_ID { get; set; }
        public string App_no { get; set; }
        public int D_ID { get; set; }
        public System.DateTime App_Date { get; set; }
        public System.TimeSpan App_Time { get; set; }
        public string P_attendence { get; set; }
        public string Cancelation { get; set; }
    }
}
