//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int D_ID { get; set; }
        public string D_name { get; set; }
        public string Specialization { get; set; }
        public string Designation { get; set; }
        public string Dept_name { get; set; }
        public string Address { get; set; }
        public string Contact_no { get; set; }
        public string E_mail { get; set; }
        public System.DateTime Joining_date { get; set; }
    }
}
