//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public int Produdct_ID { get; set; }
        public string Product_name { get; set; }
        public string Company { get; set; }
        public double Price { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Supply_date { get; set; }
        public System.DateTime Expiration_date { get; set; }
    }
}
