//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int P_ID { get; set; }
        public string P_name { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Contact_no { get; set; }
        public string Disease { get; set; }
        public string Blood_group { get; set; }
        public string Appointment_no { get; set; }
        public string Date { get; set; }
    }
}
